baseURL = "https://sretreats.github.io/"
languageCode = "en-us"
title = "SRE Treats"
theme = "sre-treats"
paginate = 6

pygmentsstyle = "monokai"

[social]
twitter= "https://twitter.com/forestryio"
github= "https://github.com/forestryio/novela-hugo-starter"
linkedin= "https://www.linkedin.com/company/forestry.io"
instagram = "#"
dribbble = "#"
youtube = "#"



[taxonomies]
author = "authors"
