name: Publish to sretreats

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        run: brew install hugo

      - name: Build
        run: hugo --minify -t sre-treats -d ../public # write outside of git path.

      - name: Deploy
        run: |
          git status
          git checkout --track origin/main
          rm -v !(*.md|*.git)
          ls -lart
          mv ../public/* .
          ls lart
          git add --all
          git commit -m "${{ github.event.head_commit.message }}"
          git push origin main
          
