name: Publish to sretreats

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        run: brew install hugo

      - name: Build
        run: hugo --minify -t sre-treats -d ../public # write outside of git path.

      - name: Deploy
        run: |
          git checkout -f --track origin/main
          $(cp *.md ../public | true)
          rm -rf *
          mv ../public/* .
          git status
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add --all
          git commit -m "[Auto commit]${{ github.event.head_commit.message }}"
          git push origin main
          
